-- MySQL Script generated by MySQL Workbench
-- Tue Nov 14 21:48:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema INT371
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `INT371` ;

-- -----------------------------------------------------
-- Schema INT371
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `INT371` DEFAULT CHARACTER SET utf8 ;
USE `INT371` ;

-- -----------------------------------------------------
-- Table `INT371`.`Levels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INT371`.`Levels` ;

CREATE TABLE IF NOT EXISTS `INT371`.`Levels` (
  `level_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`level_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INT371`.`Skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INT371`.`Skills` ;

CREATE TABLE IF NOT EXISTS `INT371`.`Skills` (
  `skill_id` INT NOT NULL auto_increment,
  `label` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `level_id` INT NOT NULL,
  PRIMARY KEY (`skill_id`),
  UNIQUE INDEX `skill_id_UNIQUE` (`skill_id` ASC) VISIBLE,
  INDEX `fk_Skills_Levels1_idx` (`level_id` ASC) VISIBLE,
  CONSTRAINT `fk_Skills_Levels1`
    FOREIGN KEY (`level_id`)
    REFERENCES `INT371`.`Levels` (`level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INT371`.`Careers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INT371`.`Careers` ;

CREATE TABLE IF NOT EXISTS `INT371`.`Careers` (
  `career_id` INT NOT NULL auto_increment,
  `label` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `short_desc` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`career_id`),
  UNIQUE INDEX `carrer_id_UNIQUE` (`career_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INT371`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INT371`.`Categories` ;

CREATE TABLE IF NOT EXISTS `INT371`.`Categories` (
  `category_id` INT NOT NULL auto_increment,
  `label` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `field_id_UNIQUE` (`category_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INT371`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INT371`.`Users` ;

CREATE TABLE IF NOT EXISTS `INT371`.`Users` (
  `user_id` INT NOT NULL auto_increment,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `desired_occupation` VARCHAR(45) NULL,
  `occupation_timestamp` DATE NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INT371`.`Organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INT371`.`Organizations` ;

CREATE TABLE IF NOT EXISTS `INT371`.`Organizations` (
  `organization_id` INT NOT NULL auto_increment,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`organization_id`),
  UNIQUE INDEX `skill_id_UNIQUE` (`organization_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INT371`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INT371`.`Courses` ;

CREATE TABLE IF NOT EXISTS `INT371`.`Courses` (
  `course_id` INT NOT NULL auto_increment,
  `label` VARCHAR(100) NOT NULL,
  `value` VARCHAR(100) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `course_level` VARCHAR(45) NOT NULL,
  `learn_hours` VARCHAR(10) NULL,
  `academic_year` VARCHAR(45) NULL,
  `course_link` VARCHAR(45) NULL,
  `organization_id` INT NOT NULL,
  PRIMARY KEY (`course_id`),
  UNIQUE INDEX `course_id_UNIQUE` (`course_id` ASC) VISIBLE,
  INDEX `fk_Courses_ Organizations1_idx` (`organization_id` ASC) VISIBLE,
  CONSTRAINT `fk_Courses_ Organizations1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `INT371`.`Organizations` (`organization_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INT371`.`Careers_Skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INT371`.`Careers_Skills` ;

CREATE TABLE IF NOT EXISTS `INT371`.`Careers_Skills` (
  `career_skills_id` INT NOT NULL auto_increment,
  `skill_id` INT NOT NULL,
  `career_id` INT NOT NULL,
  PRIMARY KEY (`career_skills_id`),
  INDEX `fk_Skills_has_Carrers_Carrers1_idx` (`career_id` ASC) VISIBLE,
  CONSTRAINT `fk_Skills_has_Carrers_Skills`
    FOREIGN KEY (`skill_id`)
    REFERENCES `INT371`.`Skills` (`skill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Skills_has_Carrers_Carrers1`
    FOREIGN KEY (`career_id`)
    REFERENCES `INT371`.`Careers` (`career_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INT371`.`Users_Careers_Interest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INT371`.`Users_Careers_Interest` ;

CREATE TABLE IF NOT EXISTS `INT371`.`Users_Careers_Interest` (
  `user_carrers_id` INT NOT NULL auto_increment,
  `career_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`user_carrers_id`),
  INDEX `fk_Carrers_has_Users_Users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Carrers_has_Users_Carrers1_idx` (`career_id` ASC) VISIBLE,
  CONSTRAINT `fk_Carrers_has_Users_Carrers1`
    FOREIGN KEY (`career_id`)
    REFERENCES `INT371`.`Careers` (`career_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrers_has_Users_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `INT371`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INT371`.`Users_Histories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INT371`.`Users_Histories` ;

CREATE TABLE IF NOT EXISTS `INT371`.`Users_Histories` (
  `history_id` INT NOT NULL auto_increment,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `course_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`history_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`history_id` ASC) VISIBLE,
  INDEX `fk_Users_Histories_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Histories_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `INT371`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INT371`.`Skills_Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INT371`.`Skills_Courses` ;

CREATE TABLE IF NOT EXISTS `INT371`.`Skills_Courses` (
  `skill_id` INT NOT NULL auto_increment,
  `course_id` INT NOT NULL,
  `skills_courses` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`skills_courses`),
  INDEX `fk_Skills_has_Courses_Courses1_idx` (`course_id` ASC) VISIBLE,
  INDEX `fk_Skills_has_Courses_Skills1_idx` (`skill_id` ASC) VISIBLE,
  CONSTRAINT `fk_Skills_has_Courses_Skills1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `INT371`.`Skills` (`skill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Skills_has_Courses_Courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `INT371`.`Courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INT371`.`Categories_Careers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `INT371`.`Categories_Careers` ;

CREATE TABLE IF NOT EXISTS `INT371`.`Categories_Careers` (
  `categories_careers_id` INT NOT NULL auto_increment,
  `category_id` INT NOT NULL,
  `career_id` INT NOT NULL,
  PRIMARY KEY (`categories_careers_id`),
  INDEX `fk_Categories_has_Careers_Careers1_idx` (`career_id` ASC) VISIBLE,
  INDEX `fk_Categories_has_Careers_Categories1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Categories_has_Careers_Categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `INT371`.`Categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categories_has_Careers_Careers1`
    FOREIGN KEY (`career_id`)
    REFERENCES `INT371`.`Careers` (`career_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
